In [1]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import keras.models as km
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints
from keras.layers import Dense, Activation

In [2]:
df=pd.read_csv(r"C:\Users\dhami\Downloads\student_performance\Student_Performance.csv")
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
df.duplicated().sum()

np.int64(127)

In [4]:
df.drop_duplicates()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [5]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [6]:
lb=LabelEncoder()
df['Extracurricular Activities']=lb.fit_transform(df['Extracurricular Activities'])

In [7]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [17]:
x = df.drop(columns=["Performance Index"])
y = df[['Performance Index']]

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=123)

In [19]:
x_train.shape

(8000, 5)

In [30]:
model = Sequential()
model.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu', input_dim = 5))
model.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'linear'))

C:\Users\dhami\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 52 (208.00 B)

 Trainable params: 52 (208.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [33]:
print(x_train.shape)
print(y_train.shape)

(8000, 5)
(8000, 1)

In [35]:
model.fit(x_train, y_train, epochs=30, batch_size=12, validation_split=0.1)
mse = model.evaluate(x_test, y_test)
print(f'Test Mean Squared Error: {mse}')

Epoch 1/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 23.5979 - val_loss: 21.4403
Epoch 2/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 22.1626 - val_loss: 20.0607
Epoch 3/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 20.7781 - val_loss: 18.7926
Epoch 4/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 19.5426 - val_loss: 17.5845
Epoch 5/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 18.2632 - val_loss: 16.4410
Epoch 6/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 17.0529 - val_loss: 15.2101
Epoch 7/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 15.8685 - val_loss: 14.1064
Epoch 8/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 14.6528 - val_loss: 13.0193
Epoch 9/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 13.4930 - val_loss: 12.0684
Epoch 10/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 12.3787 - val_loss: 11.7181
Epoch 11/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 11.2603 - val_loss: 10.0255
Epoch 12/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 10.2414 - val_loss: 9.6789
Epoch 13/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 9.2333 - val_loss: 8.0155
Epoch 14/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 8.2705 - val_loss: 7.6007
Epoch 15/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7.4443 - val_loss: 6.5388
Epoch 16/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6.6961 - val_loss: 5.8653
Epoch 17/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6.0243 - val_loss: 5.3189
Epoch 18/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5.4894 - val_loss: 4.9502
Epoch 19/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5.0940 - val_loss: 4.6423
Epoch 20/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4.7664 - val_loss: 4.3762
Epoch 21/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4.5294 - val_loss: 4.2541
Epoch 22/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.4189 - val_loss: 4.2157
Epoch 23/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4.2864 - val_loss: 4.1409
Epoch 24/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4.2703 - val_loss: 4.0995
Epoch 25/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4.2134 - val_loss: 4.1759
Epoch 26/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4.2053 - val_loss: 4.1578
Epoch 27/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.1737 - val_loss: 4.0951
Epoch 28/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4.1819 - val_loss: 4.1940
Epoch 29/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4.2018 - val_loss: 4.4238
Epoch 30/30
600/600 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.2195 - val_loss: 4.1219
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5016
Test Mean Squared Error: 4.501552581787109

In [36]:
predictions = model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [37]:
predictions

array([[80.81003 ],
       [36.166374],
       [24.40082 ],
       ...,
       [41.61257 ],
       [39.36029 ],
       [61.875374]], shape=(2000, 1), dtype=float32)