In [13]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df=pd.read_csv(r"C:\Users\dhami\Downloads\archive (19)\ml-latest-small\movies.csv")
df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [3]:
df.drop(columns=['movieId'],inplace=True)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isnull().sum()

title     0
genres    0
dtype: int64

In [6]:
df["genres"] = df["genres"].str.replace("|", " ", regex=False)

In [7]:
df

,title,genres
0,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,Jumanji (1995),Adventure Children Fantasy
2,Grumpier Old Men (1995),Comedy Romance
3,Waiting to Exhale (1995),Comedy Drama Romance
4,Father of the Bride Part II (1995),Comedy
...,...,...
9737,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy
9738,No Game No Life: Zero (2017),Animation Comedy Fantasy
9739,Flint (2017),Drama
9740,Bungo Stray Dogs: Dead Apple (2018),Action Animation
9741,Andrew Dice Clay: Dice Rules (1991),Comedy

In [8]:
tfidf = TfidfVectorizer()

In [9]:
tfidf_matrix = tfidf.fit_transform(df["genres"])

In [10]:
def recommend(movie_title, top_n=10):
    movie_idx = df[df["title"].str.lower() == movie_title.lower()].index
    if len(movie_idx) == 0:
        print("Movie not found")
        return
    movie_idx = movie_idx[0]
    selected_movie = tfidf_matrix[movie_idx]
    scores = (tfidf_matrix @ selected_movie.T).toarray().flatten()
    indices = scores.argsort()[::-1]
    print(f"\nMovies similar to '{movie_title}':\n")
    count = 0
    for idx in indices:
        if idx != movie_idx:
            print(df.iloc[idx]["title"])
            count += 1
        if count == top_n:
            break

In [11]:
recommend("Toy Story (1995)")

Movies similar to 'Toy Story (1995)':

Emperor's New Groove, The (2000)
Antz (1998)
Adventures of Rocky and Bullwinkle, The (2000)
Wild, The (2006)
Asterix and the Vikings (Astérix et les Vikings) (2006)
Turbo (2013)
Toy Story 2 (1999)
Shrek the Third (2007)
Moana (2016)
The Good Dinosaur (2015)