# Diabetes Prediction System

## Imported Libraries

In [123]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

## Data Loading

In [57]:
df=pd.read_csv(r"C:\Users\dhami\Downloads\archive (9)\diabetes_dataset.csv")
df

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1
1,48,Female,White,Highschool,Middle,Employed,Former,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,No Diabetes,0
2,60,Male,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,Type 2,1
3,74,Female,Black,Highschool,Low,Retired,Never,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,Type 2,1
4,46,Male,White,Graduate,Middle,Retired,Never,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,Type 2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,Male,Other,Graduate,Upper-Middle,Unemployed,Former,1,136,8.3,...,45,150,116,113,109,14.58,5.55,26.0,Pre-Diabetes,0
99996,41,Female,White,Graduate,Middle,Employed,Never,3,76,8.8,...,55,123,146,96,146,9.02,5.97,24.4,Pre-Diabetes,0
99997,57,Female,Black,No formal,Upper-Middle,Employed,Former,4,121,9.9,...,50,111,184,93,132,2.57,5.21,27.6,No Diabetes,0
99998,47,Female,Black,Highschool,Lower-Middle,Retired,Never,3,52,5.9,...,68,91,116,106,117,9.81,5.53,26.4,Pre-Diabetes,0
99999,52,Female,White,Postgraduate,Middle,Employed,Never,1,248,2.7,...,31,183,87,91,142,15.93,5.73,27.9,Pre-Diabetes,0

## Data Information Gathering

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 100000 non-null  int64
 1   gender                              100000 non-null  object
 2   ethnicity                           100000 non-null  object
 3   education_level                     100000 non-null  object
 4   income_level                        100000 non-null  object
 5   employment_status                   100000 non-null  object
 6   smoking_status                      100000 non-null  object
 7   alcohol_consumption_per_week        100000 non-null  int64
 8   physical_activity_minutes_per_week  100000 non-null  int64
 9   diet_score                          100000 non-null  float64
 10  sleep_hours_per_day                 100000 non-null  float64
 11  screen_time_hours_per_day           100000 non-null  float64
 12  family_history_diabetes             100000 non-null  int64
 13  hypertension_history                100000 non-null  int64
 14  cardiovascular_history              100000 non-null  int64
 15  bmi                                 100000 non-null  float64
 16  waist_to_hip_ratio                  100000 non-null  float64
 17  systolic_bp                         100000 non-null  int64
 18  diastolic_bp                        100000 non-null  int64
 19  heart_rate                          100000 non-null  int64
 20  cholesterol_total                   100000 non-null  int64
 21  hdl_cholesterol                     100000 non-null  int64
 22  ldl_cholesterol                     100000 non-null  int64
 23  triglycerides                       100000 non-null  int64
 24  glucose_fasting                     100000 non-null  int64
 25  glucose_postprandial                100000 non-null  int64
 26  insulin_level                       100000 non-null  float64
 27  hba1c                               100000 non-null  float64
 28  diabetes_risk_score                 100000 non-null  float64
 29  diabetes_stage                      100000 non-null  object
 30  diagnosed_diabetes                  100000 non-null  int64
dtypes: float64(8), int64(16), object(7)
memory usage: 23.7+ MB

In [59]:
df.shape

(100000, 31)

In [60]:
df.head()

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1
1,48,Female,White,Highschool,Middle,Employed,Former,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,No Diabetes,0
2,60,Male,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,Type 2,1
3,74,Female,Black,Highschool,Low,Retired,Never,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,Type 2,1
4,46,Male,White,Graduate,Middle,Retired,Never,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,Type 2,1

In [61]:
df.tail()

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
99995,46,Male,Other,Graduate,Upper-Middle,Unemployed,Former,1,136,8.3,...,45,150,116,113,109,14.58,5.55,26.0,Pre-Diabetes,0
99996,41,Female,White,Graduate,Middle,Employed,Never,3,76,8.8,...,55,123,146,96,146,9.02,5.97,24.4,Pre-Diabetes,0
99997,57,Female,Black,No formal,Upper-Middle,Employed,Former,4,121,9.9,...,50,111,184,93,132,2.57,5.21,27.6,No Diabetes,0
99998,47,Female,Black,Highschool,Lower-Middle,Retired,Never,3,52,5.9,...,68,91,116,106,117,9.81,5.53,26.4,Pre-Diabetes,0
99999,52,Female,White,Postgraduate,Middle,Employed,Never,1,248,2.7,...,31,183,87,91,142,15.93,5.73,27.9,Pre-Diabetes,0

In [62]:
df.min(numeric_only=True)

age                                    18.00
alcohol_consumption_per_week            0.00
physical_activity_minutes_per_week      0.00
diet_score                              0.00
sleep_hours_per_day                     3.00
screen_time_hours_per_day               0.50
family_history_diabetes                 0.00
hypertension_history                    0.00
cardiovascular_history                  0.00
bmi                                    15.00
waist_to_hip_ratio                      0.67
systolic_bp                            90.00
diastolic_bp                           50.00
heart_rate                             40.00
cholesterol_total                     100.00
hdl_cholesterol                        20.00
ldl_cholesterol                        50.00
triglycerides                          30.00
glucose_fasting                        60.00
glucose_postprandial                   70.00
insulin_level                           2.00
hba1c                                   4.00
diabetes_risk_score                     2.70
diagnosed_diabetes                      0.00
dtype: float64

In [63]:
df.max(numeric_only=True)

age                                    90.00
alcohol_consumption_per_week           10.00
physical_activity_minutes_per_week    833.00
diet_score                             10.00
sleep_hours_per_day                    10.00
screen_time_hours_per_day              16.80
family_history_diabetes                 1.00
hypertension_history                    1.00
cardiovascular_history                  1.00
bmi                                    39.20
waist_to_hip_ratio                      1.06
systolic_bp                           179.00
diastolic_bp                          110.00
heart_rate                            105.00
cholesterol_total                     318.00
hdl_cholesterol                        98.00
ldl_cholesterol                       263.00
triglycerides                         344.00
glucose_fasting                       172.00
glucose_postprandial                  287.00
insulin_level                          32.22
hba1c                                   9.80
diabetes_risk_score                    67.20
diagnosed_diabetes                      1.00
dtype: float64

In [64]:
df.mean(numeric_only=True)

age                                    50.120410
alcohol_consumption_per_week            2.003670
physical_activity_minutes_per_week    118.911640
diet_score                              5.994787
sleep_hours_per_day                     6.997818
screen_time_hours_per_day               5.996468
family_history_diabetes                 0.219410
hypertension_history                    0.250800
cardiovascular_history                  0.079200
bmi                                    25.612653
waist_to_hip_ratio                      0.856078
systolic_bp                           115.799610
diastolic_bp                           75.232490
heart_rate                             69.632870
cholesterol_total                     185.978110
hdl_cholesterol                        54.042790
ldl_cholesterol                       103.000430
triglycerides                         121.462650
glucose_fasting                       111.117120
glucose_postprandial                  160.035050
insulin_level                           9.061242
hba1c                                   6.520776
diabetes_risk_score                    30.222362
diagnosed_diabetes                      0.599980
dtype: float64

In [65]:
df.median(numeric_only=True)

age                                    50.00
alcohol_consumption_per_week            2.00
physical_activity_minutes_per_week    100.00
diet_score                              6.00
sleep_hours_per_day                     7.00
screen_time_hours_per_day               6.00
family_history_diabetes                 0.00
hypertension_history                    0.00
cardiovascular_history                  0.00
bmi                                    25.60
waist_to_hip_ratio                      0.86
systolic_bp                           116.00
diastolic_bp                           75.00
heart_rate                             70.00
cholesterol_total                     186.00
hdl_cholesterol                        54.00
ldl_cholesterol                       102.00
triglycerides                         121.00
glucose_fasting                       111.00
glucose_postprandial                  160.00
insulin_level                           8.79
hba1c                                   6.52
diabetes_risk_score                    29.00
diagnosed_diabetes                      1.00
dtype: float64

In [66]:
df.count(numeric_only=True)

age                                   100000
alcohol_consumption_per_week          100000
physical_activity_minutes_per_week    100000
diet_score                            100000
sleep_hours_per_day                   100000
screen_time_hours_per_day             100000
family_history_diabetes               100000
hypertension_history                  100000
cardiovascular_history                100000
bmi                                   100000
waist_to_hip_ratio                    100000
systolic_bp                           100000
diastolic_bp                          100000
heart_rate                            100000
cholesterol_total                     100000
hdl_cholesterol                       100000
ldl_cholesterol                       100000
triglycerides                         100000
glucose_fasting                       100000
glucose_postprandial                  100000
insulin_level                         100000
hba1c                                 100000
diabetes_risk_score                   100000
diagnosed_diabetes                    100000
dtype: int64

In [67]:
df.std(numeric_only=True)

age                                   15.604600
alcohol_consumption_per_week           1.417779
physical_activity_minutes_per_week    84.409662
diet_score                             1.780954
sleep_hours_per_day                    1.094622
screen_time_hours_per_day              2.468406
family_history_diabetes                0.413849
hypertension_history                   0.433476
cardiovascular_history                 0.270052
bmi                                    3.586705
waist_to_hip_ratio                     0.046837
systolic_bp                           14.284073
diastolic_bp                           8.204250
heart_rate                             8.371954
cholesterol_total                     32.013005
hdl_cholesterol                       10.267374
ldl_cholesterol                       33.390256
triglycerides                         43.372619
glucose_fasting                       13.595610
glucose_postprandial                  30.935472
insulin_level                          4.954060
hba1c                                  0.813921
diabetes_risk_score                    9.061505
diagnosed_diabetes                     0.489904
dtype: float64

In [68]:
df.describe()

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,bmi,...,cholesterol_total,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diagnosed_diabetes
count,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50.12041,2.003670,118.911640,5.994787,6.997818,5.996468,0.219410,0.250800,0.079200,25.612653,...,185.978110,54.042790,103.000430,121.462650,111.11712,160.035050,9.061242,6.520776,30.222362,0.599980
std,15.60460,1.417779,84.409662,1.780954,1.094622,2.468406,0.413849,0.433476,0.270052,3.586705,...,32.013005,10.267374,33.390256,43.372619,13.59561,30.935472,4.954060,0.813921,9.061505,0.489904
min,18.00000,0.000000,0.000000,0.000000,3.000000,0.500000,0.000000,0.000000,0.000000,15.000000,...,100.000000,20.000000,50.000000,30.000000,60.00000,70.000000,2.000000,4.000000,2.700000,0.000000
25%,39.00000,1.000000,57.000000,4.800000,6.300000,4.300000,0.000000,0.000000,0.000000,23.200000,...,164.000000,47.000000,78.000000,91.000000,102.00000,139.000000,5.090000,5.970000,23.800000,0.000000
50%,50.00000,2.000000,100.000000,6.000000,7.000000,6.000000,0.000000,0.000000,0.000000,25.600000,...,186.000000,54.000000,102.000000,121.000000,111.00000,160.000000,8.790000,6.520000,29.000000,1.000000
75%,61.00000,3.000000,160.000000,7.200000,7.700000,7.700000,0.000000,1.000000,0.000000,28.000000,...,208.000000,61.000000,126.000000,151.000000,120.00000,181.000000,12.450000,7.070000,35.600000,1.000000
max,90.00000,10.000000,833.000000,10.000000,10.000000,16.800000,1.000000,1.000000,1.000000,39.200000,...,318.000000,98.000000,263.000000,344.000000,172.00000,287.000000,32.220000,9.800000,67.200000,1.000000

## Data Cleaning

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
df.isnull().sum()

age                                   0
gender                                0
ethnicity                             0
education_level                       0
income_level                          0
employment_status                     0
smoking_status                        0
alcohol_consumption_per_week          0
physical_activity_minutes_per_week    0
diet_score                            0
sleep_hours_per_day                   0
screen_time_hours_per_day             0
family_history_diabetes               0
hypertension_history                  0
cardiovascular_history                0
bmi                                   0
waist_to_hip_ratio                    0
systolic_bp                           0
diastolic_bp                          0
heart_rate                            0
cholesterol_total                     0
hdl_cholesterol                       0
ldl_cholesterol                       0
triglycerides                         0
glucose_fasting                       0
glucose_postprandial                  0
insulin_level                         0
hba1c                                 0
diabetes_risk_score                   0
diabetes_stage                        0
diagnosed_diabetes                    0
dtype: int64

In [71]:
df.tail()

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
99995,46,Male,Other,Graduate,Upper-Middle,Unemployed,Former,1,136,8.3,...,45,150,116,113,109,14.58,5.55,26.0,Pre-Diabetes,0
99996,41,Female,White,Graduate,Middle,Employed,Never,3,76,8.8,...,55,123,146,96,146,9.02,5.97,24.4,Pre-Diabetes,0
99997,57,Female,Black,No formal,Upper-Middle,Employed,Former,4,121,9.9,...,50,111,184,93,132,2.57,5.21,27.6,No Diabetes,0
99998,47,Female,Black,Highschool,Lower-Middle,Retired,Never,3,52,5.9,...,68,91,116,106,117,9.81,5.53,26.4,Pre-Diabetes,0
99999,52,Female,White,Postgraduate,Middle,Employed,Never,1,248,2.7,...,31,183,87,91,142,15.93,5.73,27.9,Pre-Diabetes,0

In [72]:
df = df.drop(['diabetes_stage', 'diabetes_risk_score'], axis=1)
selected_columns = [
    'hba1c',
    'glucose_fasting',
    'bmi',
    'age',
    'physical_activity_minutes_per_week',
    'gender',
    'family_history_diabetes',
    'diagnosed_diabetes'
]
df = df[selected_columns]
df

,hba1c,glucose_fasting,bmi,age,physical_activity_minutes_per_week,gender,family_history_diabetes,diagnosed_diabetes
0,8.18,136,30.5,58,215,Male,0,1
1,5.63,93,23.1,48,143,Female,0,0
2,7.51,118,22.2,60,57,Male,1,1
3,9.03,139,26.8,74,49,Female,0,1
4,7.20,137,21.2,46,109,Male,0,1
...,...,...,...,...,...,...,...,...
99995,5.55,113,29.8,46,136,Male,0,0
99996,5.97,96,26.5,41,76,Female,0,0
99997,5.21,93,25.6,57,121,Female,0,0
99998,5.53,106,26.8,47,52,Female,0,0
99999,5.73,91,30.3,52,248,Female,0,0

In [73]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print(df.head())

Shape: (100000, 8)
Columns: ['hba1c', 'glucose_fasting', 'bmi', 'age', 'physical_activity_minutes_per_week', 'gender', 'family_history_diabetes', 'diagnosed_diabetes']
   hba1c  glucose_fasting   bmi  age  physical_activity_minutes_per_week  \
0   8.18              136  30.5   58                                 215
1   5.63               93  23.1   48                                 143
2   7.51              118  22.2   60                                  57
3   9.03              139  26.8   74                                  49
4   7.20              137  21.2   46                                 109

   gender  family_history_diabetes  diagnosed_diabetes
0    Male                        0                   1
1  Female                        0                   0
2    Male                        1                   1
3  Female                        0                   1
4    Male                        0                   1

In [74]:
le=LabelEncoder()
df['gender']=le.fit_transform(df['gender'])

In [75]:
df

,hba1c,glucose_fasting,bmi,age,physical_activity_minutes_per_week,gender,family_history_diabetes,diagnosed_diabetes
0,8.18,136,30.5,58,215,1,0,1
1,5.63,93,23.1,48,143,0,0,0
2,7.51,118,22.2,60,57,1,1,1
3,9.03,139,26.8,74,49,0,0,1
4,7.20,137,21.2,46,109,1,0,1
...,...,...,...,...,...,...,...,...
99995,5.55,113,29.8,46,136,1,0,0
99996,5.97,96,26.5,41,76,0,0,0
99997,5.21,93,25.6,57,121,0,0,0
99998,5.53,106,26.8,47,52,0,0,0
99999,5.73,91,30.3,52,248,0,0,0

## random forest

In [110]:
clf=RandomForestClassifier()

In [111]:
clf.fit(x_train , y_train)

RandomForestClassifier()

In [112]:
clf.score(x_train , y_train)

0.9999625

In [113]:
clf.score(x_test , y_test)

0.92005

In [114]:
y_pred = clf.predict(x_test)

In [115]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91      8077
           1       1.00      0.87      0.93     11923

    accuracy                           0.92     20000
   macro avg       0.92      0.93      0.92     20000
weighted avg       0.93      0.92      0.92     20000

## Hyperparameter Tuning

In [116]:
param_grid = {
    'n_estimators': [50, 100],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [4, 6, 8],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

In [117]:
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [118]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [4, 6, 8],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100]},
             scoring='accuracy')

In [119]:
print("Best Parameters Found:", grid_search.best_params_)
print("Best Accuracy Score:", grid_search.best_score_)

Best Parameters Found: {'max_depth': 4, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}
Best Accuracy Score: 0.9213125

In [120]:
best_rf_model = grid_search.best_estimator_

In [121]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(best_rf_model, file)