In [35]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
df = pd.read_csv(r"C:\Users\dhami\Downloads\sentiment analysis\sentiment_analysis.csv")
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram
...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram

In [37]:
df.duplicated().sum()

np.int64(105)

In [38]:
df.drop_duplicates(inplace=True)

In [39]:
df.isnull().sum()

Year             0
Month            0
Day              0
Time of Tweet    0
text             0
sentiment        0
Platform         0
dtype: int64

In [8]:
df.drop(columns=['Year','Month','Day','Time of Tweet','Platform'],inplace=True)

In [9]:
lb=LabelEncoder()
df['sentiment']=lb.fit_transform(df['sentiment'])

In [10]:
df

                                                  text  sentiment
0                What a great day!!! Looks like dream.          2
1       I feel sorry, I miss you here in the sea beach          2
2                                       Don't angry me          0
3    We attend in the class just for listening teac...          0
4                    Those who want to go, let them go          0
..                                                 ...        ...
494  According to , a quarter of families under six...          0
495      the plan to not spend money is not going well          0
496    uploading all my bamboozle pictures of facebook          1
497   congratulations ! you guys finish a month ear...          2
498   actually, I wish I was back in Tahoe.  I miss...          0

[394 rows x 2 columns]

In [11]:
pip install nltk

Requirement already satisfied: nltk in c:\users\dhami\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\dhami\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\dhami\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dhami\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\dhami\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\dhami\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dhami\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dhami\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
stop_words=stopwords.words("english")
ps=PorterStemmer()

In [15]:
def preprocessing(text):
    text=text.lower()
    token=nltk.word_tokenize(text)
    new=[]
    for i in token:
        if i not in stop_words and i not in string.punctuation:
            stemmer=ps.stem(i)
            new.append(stemmer)
        return " ".join(new)

In [16]:
df['clean']=df['text'].apply(preprocessing)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
tfidf = TfidfVectorizer(max_features=5000)

In [21]:
x = tfidf.fit_transform(df['clean'])
y = df['sentiment']

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=42)

In [23]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [25]:
y_pred = model.predict(x_test)

In [27]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.3924050632911392
              precision    recall  f1-score   support

           0       1.00      0.05      0.10        20
           1       0.36      0.86      0.51        28
           2       0.55      0.19      0.29        31

    accuracy                           0.39        79
   macro avg       0.63      0.37      0.30        79
weighted avg       0.59      0.39      0.32        79

In [34]:
new_text = ["I like this product"]
clean_text = preprocessing(new_text[0])
vector = tfidf.transform([clean_text])
prediction = model.predict(vector)
print("Predicted Sentiment:",
      lb.inverse_transform(prediction)[0])

Predicted Sentiment: neutral